Updated-Workflow

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -25,7 +25,13 @@ jobs:
         pip install -r requirements.txt
 
     - name: Run training script
-      run: python src/train.py
+      run: USE_MLFLOW=false python src/train.py  # disable MLflow for CI
+
+    - name: Check if model file exists
+      run: |
+        echo "Checking models directory..."
+        ls -la models
+        test -f models/best_model.pkl || (echo "Model file not found!" && exit 1)
 
     - name: Build Docker image
       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rainfall-prediction:latest .
